### ISSUE TITLE
Change script to use any smart template lib

### ISSUE THREAD

**Issue by thiagosalles** [thiagosalles/newad_notifier#14]

**Comment by wjanoti** [comment]
Alguém já está vendo isso?

**Comment by thiagosalles** [comment]
Eu comecei a olhar pra fazer com ERB, mas estou tentando fazer o deploy pro Heroku, pode fazer se quiser :)

**Comment by wjanoti** [comment]
Vou tentar fazer com o Liquid então e te falo.
